export const ADD_PRODUCT_TO_LIST = "ADD_PRODUCT_TO_LIST";
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_FAILD = "PRODUCT_LIST_FAILD";
export const PRODUCT_LIST_RECIVE = "PRODUCT_LIST_RECIVE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const POST_PRODUCT = "POST_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
